### ISSUE TITLE
Unable to parse data files from MySQL 8.0

### ISSUE THREAD

**Issue by qlh2561808384** [jeremycole/innodb_ruby#143]
➜ data innodb_space -s ibdata1 -T sakila/actor space-indexes
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /opt/homebrew/bin in PATH, mode 040777
/Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page::FspHdrXdes:0x000000010412f368> (NoMethodError)
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/index.rb:19:in `initialize'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:312:in `new'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:312:in `index'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:287:in `data_dictionary_index'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:333:in `each_table'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:376:in `each'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:376:in `select'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:376:in `object_by_field'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:392:in `table_by_name'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/system.rb:97:in `space_by_table_name'
	from /Users/qlh/.gem/ruby/2.6.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1603:in `<top (required)>'
	from /usr/local/bin/innodb_space:23:in `load'
	from /usr/local/bin/innodb_space:23:in `<main>'
➜ data ls
#ib_16384_0.dblwr     binlog.000011         binlog.000017         client-cert.pem       ibtmp1                private_key.pem       test                  test_obp_market       undo_001
#ib_16384_1.dblwr     binlog.000012         binlog.000018         client-key.pem        mysql                 public_key.pem        test_obp_account      test_obp_midware      undo_002
#innodb_temp          binlog.000013         binlog.000019         ib_buffer_pool        mysql.ibd             sakila                test_obp_billplatform test_obp_order
auto.cnf              binlog.000014         binlog.index          ib_logfile0           mysqld.local.err      server-cert.pem       test_obp_configure    test_obp_settlement
binlog.000009         binlog.000015         ca-key.pem            ib_logfile1           mysqld.local.pid      server-key.pem        test_obp_data         test_obp_supplier
binlog.000010         binlog.000016         ca.pem                ibdata1               performance_schema    sys                   test_obp_goods        test_obp_user

**Comment by qlh2561808384** [comment]
Hello, how can I solve this problem?

**Comment by qlh2561808384** [comment]
Hello, how can I solve this problem?

**Comment by qlh2561808384** [comment]
I am using mysql .
mysql Ver 8.0.29 for macos12 on arm64 (MySQL Community Server - GPL)

**Comment by jeremycole** [comment]
MySQL 8.0 is not supported, see https://github.com/jeremycole/innodb_ruby/issues/97.
