### ISSUE TITLE
undefined method `fsp_header'

### ISSUE THREAD

**Issue by yunsonbai** [jeremycole/innodb_ruby#169]
hello, I have a problem when use  innodb_space -f yst.ibd space-page-type-regions
The error:
/usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:272:in `fsp': undefined method `fsp_header' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:150:in `fsp_flags'
	from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:73:in `initialize'
	from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1612:in `new'
	from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1612:in `<top (required)>'
	from /usr/local/bin/innodb_space:23:in `load'
	from /usr/local/bin/innodb_space:23:in `<main>'

mariadb version is :  10.5.15
innodb version is: 10.5.15

**Comment by jeremycole** [comment]
MariaDB 10.5 is not supported, see #119.
