### ISSUE TITLE
innodb_space:754: syntax error, unexpected '.'

### ISSUE THREAD

**Issue by myabce** [jeremycole/innodb_ruby#193]
# /root/innodb_ruby-master/bin/innodb_space -f abc/t1.ibd space-indexes
/root/innodb_ruby-master/bin/innodb_space:754: syntax error, unexpected '.'
...innodb_system.data_dictionary&.each_data_dictionary_index do...
...                               ^
/root/innodb_ruby-master/bin/innodb_space:1645: syntax error, unexpected '.'
...(Innodb::Page::Index) && page&.root?
...                               ^
# hostnamectl
   Static hostname: vm1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 2008ec27d9ce57718c5d875e1245333e
           Boot ID: bf593b5f8b204a345d5ecc766893fcd2
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.71.1.el7.x86_64
      Architecture: x86-64

**Comment by jeremycole** [comment]
It would appear that you're attempting to use a very old version of Ruby, before 2.3 when the safe navigation operator (`&.`) was introduced. That's definitely not going to work.
