### ISSUE TITLE
undefined method `record_describer=' errors

### ISSUE THREAD

**Issue by zmy2022** [jeremycole/innodb_ruby#195]
### Hello, I am a junior developer. When I use innodb_ruby to view page structure information, I get the following error

innodb_space -s ibdata1 -T capp/pdt_check_record -p 3 page-dump
/usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page::FspHdrXdes size=16384, space_id=0, offset=0, type=:FSP_HDR, prev=80026, next=1, checksum_valid?=true, checksum_type=:crc32, torn?=false, misplaced?=false> (NoMethodError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/index.rb:19:in `initialize'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:312:in `new'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:312:in `index'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:287:in `data_dictionary_index'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:355:in `each_index'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/data_dictionary.rb:425:in `each_index_by_space_id'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:321:in `each_index_root_page_number'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:341:in `each_index'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/bin/innodb_space:188:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/bin/innodb_space:188:in `to_a'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/bin/innodb_space:188:in `block in system_spaces'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/bin/innodb_space:192:in `system_spaces'
	from /usr/local/lib/ruby/gems/3.0.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1714:in `<top (required)>'
	from /usr/local/bin/innodb_space:23:in `load'
	from /usr/local/bin/innodb_space:23:in `<main>'

### The following is where the source code reports errors You can see that record_describer is set to nil in the initialize method. What should I do in this case? 

      4 module Innodb
      5   class Index
      6     attr_reader :root
      7     attr_reader :space
      8     attr_accessor :record_describer
      9 
     10     FSEG_LIST_NAMES = %i[
     11       internal
     12       leaf
     13     ].freeze
     14 
     15     def initialize(space, root_page_number, record_describer = nil)
     16       @space = space
     17       @record_describer = record_describer || space.record_describer
     18 
     19       @root = page(root_page_number)
     20 
     21       raise "Page #{root_page_number} couldn't be read" unless @root
     22 
     23       # The root page should be an index page.
     24       raise "Page #{root_page_number} is a #{@root.type} page, not an INDEX page" unless @root.type == :INDEX
     25 
     26       # The root page should be the only page at its level.
     27       raise "Page #{root_page_number} does not appear to be an index root" if @root.prev || @root.next
     28     end

**Comment by zmy2022** [comment]
### I saw in another question answer that you added the following code
class Innodb::RecordDescriber::MyTable < Innodb::RecordDescriber
  def self.cursor_sendable_description(page)
    {
      :type => :clustered,
      :key => [
        [:INT, :UNSIGNED, :NOT_NULL],
      ],
      :row => [
        ["CHAR(255)", :NOT_NULL],
      ],
    }
  end
end

### Does this code add record_describer? But I’m not familiar with the Ruby language. Can you tell me where this code should be placed to make it effective?

**Comment by zmy2022** [comment]
###    I tried changing the version but still got the same error. My mysql version is 8 and the ruby ​​version is 2.6.  In line 34 of the code page.record_describer = @record_describer this record_describer is empty so an error is reported. What should I do?

     15     def initialize(space, root_page_number, record_describer = nil)
     16       @space = space
     17       @record_describer = record_describer || space.record_describer
     18 
     19       @root = page(root_page_number)
     20 
     21       raise "Page #{root_page_number} couldn't be read" unless @root
     22 
     23       # The root page should be an index page.
     24       raise "Page #{root_page_number} is a #{@root.type} page, not an INDEX page" unless @root.type == :INDEX
     25 
     26       # The root page should be the only page at its level.
     27       raise "Page #{root_page_number} does not appear to be an index root" if @root.prev || @root.next
     28     end
     29 
     30     def page(page_number)
     31       page = @space.page(page_number)
     32       raise "Page #{page_number} couldn't be read" unless page
     33 
     34       page.record_describer = @record_describer
     35       page
     36     end

**Comment by zmy2022** [comment]
### I use innodb_ruby to parse the page structure in order to understand that when a row overflow occurs, the overflow data is stored in the overflow page. In this case, a query is performed to find out that the overflow column of this row records the pointer of the overflow page and is read according to the pointer. When fetching data, is this IO sequential IO or random IO? Are the pages read by mysql this time and the overflow pages in the records of this page continuous on the disk?

**Comment by zmy2022** [comment]
我真吐了兄弟 整到最后 原来你不支持mysql8啊  哥们 你就不能把这写到readme里面吗

**Comment by zmy2022** [comment]
我真吐了啊 兄弟 最后发现不支持mysql8啊 哥们 能不能把这写到readme里面啊

**Comment by jeremycole** [comment]
Correct that MySQL >5.7 is not currently supported; there were very drastic changes to the data dictionary that require a lot of new code and refactoring to support it. This work is partly done but the current status is just unsupported.

> ### I use innodb_ruby to parse the page structure in order to understand that when a row overflow occurs, the overflow data is stored in the overflow page. In this case, a query is performed to find out that the overflow column of this row records the pointer of the overflow page and is read according to the pointer. When fetching data, is this IO sequential IO or random IO? Are the pages read by mysql this time and the overflow pages in the records of this page continuous on the disk?

I don't think this is an appropriate thing to use `innodb_ruby` for, because the behavior of `innodb_ruby` is different than that of InnoDB. Your question is about the _behavior_ and not necessarily the data structures, it would be best answered by examining the InnoDB code. In MySQL 8.0, several new LOB types were introduced which complicate this somewhat as the behavior will be different for each, but see the following page types in the InnoDB code: `BLOB`, `ZBLOB`, `LOB_INDEX`, `LOB_INDEX`, `LOB_FIRST`, `ZLOB_FIRST`, `ZLOB_DATA`, `ZLOB_INDEX`, `ZLOB_FRAG`, `ZLOB_FRAG_ENTRY`. Unfortunately, IMO, they have made quite a mess of things, too.

**Comment by zmy2022** [comment]
> It is correct to point out that MySQL >5.7 is not currently supported; The data dictionary has changed very drastically and requires a lot of new code and refactoring to support it. This work has been partially done, but the current state is just not supported.
> 
> > ### I use innodb_ruby to parse the page structure so that I understand that when a row overflow occurs, the overflow data is stored in the overflow page. In this case, execute a query to find out that the overflow column of this row records the pointer to the overflow page, and read it based on the pointer. When fetching data, is this IO sequential IO or random IO? Are the pages read by mysql this time and the overflow pages in that page record consecutively on disk?
> 
> I don't think that's a suitable use because of the different behavior of InnoDB. Your question is about _behavior_, not necessarily data structures, and is best answered by examining the InnoDB code. In MySQL 8.0, several new LOB types were introduced, which complicates the situation a bit because each type behaves differently, but see the following page types in the InnoDB code: Unfortunately, IMO, they also make a mess of things.`innodb_ruby``innodb_ruby``BLOB``ZBLOB``LOB_INDEX``LOB_INDEX``LOB_FIRST``ZLOB_FIRST``ZLOB_DATA``ZLOB_INDEX``ZLOB_FRAG``ZLOB_FRAG_ENTRY`

**Comment by zmy2022** [comment]
Indeed, I should focus on behavior rather than structure for this question
