### ISSUE TITLE
`read_and_advance': undefined method `bytes' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by gurusami** [jeremycole/innodb_ruby#23]
Hi.  I am facing the following issue.  Any idea what could be wrong?

$ innodb_space -s ibdata1 undo-history-summary
Page    Offset  Transaction   Type                Table
1283    771     1204          delete              ipworks/ENUMDNSCHED
1318    272     1204          delete              ipworks/ENUMDNSCHED
1250    1007    1204          delete              ipworks/ENUMDNSCHED
1049    1745    1204          delete              ipworks/ENUMDNSCHED
1251    774     1204          delete              ipworks/ENUMDNSCHED
601     0                                         
1243    1279    1204          delete              ipworks/ENUMDNSCHED
1257    1281    1204          delete              ipworks/ENUMDNSCHED
1051    1005    1204          delete              ipworks/ENUMDNSCHED
1319    272     1204          delete              ipworks/ENUMDNSCHED
1264    1012    1204          delete              ipworks/ENUMDNSCHED
1284    1030    1204          delete              ipworks/ENUMDNSCHED
1332    515     1204          delete              ipworks/ENUMDNSCHED
1053    781     1204          delete              ipworks/ENUMDNSCHED
1269    792     1204          delete              ipworks/ENUMDNSCHED
1054    2516    1204          delete              ipworks/ENUMDNSCHED
1055    1482    1204          delete              ipworks/ENUMDNSCHED
1056    507     1204          delete              ipworks/ENUMDNSCHED
1057    501     1204          delete              ipworks/ENUMDNSCHED
1336    272     1204          delete              ipworks/ENUMDNSCHED
1281    1443    1204          delete              ipworks/ENUMDNSCHED
1289    1776    1204          delete              ipworks/ENUMDNSCHED
1232    1272    1204          delete              ipworks/ENUMDNSCHED
1277    0                                         
/var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/util/buffer_cursor.rb:217:in `read_and_advance': undefined method `bytes' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/util/buffer_cursor.rb:259:in `get_uint16'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:70:in `block (2 levels) in header'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/util/buffer_cursor.rb:136:in `name'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:70:in `block in header'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/util/buffer_cursor.rb:136:in `name'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:68:in `header'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:88:in `type'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:98:in `get'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_record.rb:109:in `next'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_log.rb:85:in `next_undo_record'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/undo_log.rb:104:in `undo_record'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/history_list.rb:39:in `undo_record'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/history_list.rb:87:in `each_undo_record'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/lib/innodb/history_list.rb:102:in `each_undo_record'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/bin/innodb_space:1052:in `block in undo_history_summary'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/bin/innodb_space:1051:in `each'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/bin/innodb_space:1051:in `undo_history_summary'
        from /var/lib/gems/2.1.0/gems/innodb_ruby-0.9.12/bin/innodb_space:1512:in `<top (required)>'
        from /usr/local/bin/innodb_space:23:in `load'
        from /usr/local/bin/innodb_space:23:in `<main>'
$

**Comment by jeremycole** [comment]
This is basically expected when dealing with undo records. Unfortunately it's not possible for `innodb_ruby` to tell if an undo record is valid or not, so it tries to blindly follow them and later may find out that the record is invalid because some read will fail.

**Comment by gurusami** [comment]
Thank you for the response.  So, this confirms that the undo log is corrupted?

**Comment by jeremycole** [comment]
No, not really. Undo records are cleaned up by InnoDB in the background, but many links to them are left around, because in normal operation InnoDB would never follow those links because they are for transactions too old to have current undo history. However since `innodb_ruby` is running on the outside of InnoDB, it can't know whether the links are valid.

It's likely that your database and the undo logs in it are just fine.
