### ISSUE TITLE
[FEATURE REQUEST] Add support for parsing the output of `SHOW ENGINE INNODB STATUS`

### ISSUE THREAD

**Issue by KirilAngov** [jeremycole/innodb_ruby#24]
I know this might be outside of the scope of the gem but I think these kind of go hand in hand and I would love to see this functionality in innodb_ruby

The idea is modeled after
  * http://linux.die.net/man/3/innodbparser
  * https://github.com/dgoodlad/innodbparser

**Comment by jeremycole** [comment]
Thanks for the suggestion, but I think that is well outside the scope of this code and would be well served enough by its own ruby library.
