### ISSUE TITLE
space-index-pages-summary errors if table space has never had data

### ISSUE THREAD

**Issue by phil-hildebrand** [jeremycole/innodb_ruby#25]
I haven't looked into the code, but it appears that the space-index-pages-summary option to innodb_space errors when examining a table that has been created, but has no data.

Repro Steps:

mysql> create table my_test (id int auto_increment primary key, my_val varchar(10)) engine=innodb;
Query OK, 0 rows affected (0.01 sec)
mysql> select * from my_test;
Empty set (0.00 sec)
mysql> quit
Bye

innodb_space -f my_test.ibd space-index-pages-summary | head -n 10
/var/lib/gems/1.8/gems/innodb_ruby-0.9.12/lib/innodb/space.rb:113:in `raw_fsp_header_flags': Something is very wrong; Page 0 does not seem to be type FSP_HDR; got page type 0 but expected 8 (RuntimeError)
	from /var/lib/gems/1.8/gems/innodb_ruby-0.9.12/lib/innodb/space.rb:139:in `fsp_flags'
	from /var/lib/gems/1.8/gems/innodb_ruby-0.9.12/lib/innodb/space.rb:57:in `initialize'
	from /var/lib/gems/1.8/gems/innodb_ruby-0.9.12/bin/innodb_space:1364:in `new'
	from /var/lib/gems/1.8/gems/innodb_ruby-0.9.12/bin/innodb_space:1364
	from /usr/local/bin/innodb_space:19:in `load'
	from /usr/local/bin/innodb_space:19

Mysql version:  5.6.22-72.0-log Percona Server (GPL), Release 72.0, Revision 738
Linux: 3.5.0-54-generic #81~precise1-Ubuntu SMP

**Comment by phil-hildebrand** [comment]
Note: My use case is looking across all our tables for any tables that have no data.  Because we have ~1 million tables per MySQL instance, using the information schema would not be near as efficient as the tool you wrote

**Comment by jeremycole** [comment]
I think this is just because the page 0 hasn't been flushed to disk yet. Immediately after making changes in InnoDB, they may not be reflected by innodb_ruby because the pages haven't been flushed, and that's not exactly a bug...

**Comment by darnaut** [comment]
You can use [INNODB_BUFFER_PAGE](https://dev.mysql.com/doc/refman/5.6/en/innodb-buffer-page-table.html) to wait for the page to be flushed to disk.
