### ISSUE TITLE
illustrate commands output to image file

### ISSUE THREAD

**Issue by lefred** [jeremycole/innodb_ruby#26]
It would be so great if we could output the result of the *illustrate command directly to an image (that I could include in documentation/reports). 

For example, I'm a big fan of space-lsn-age-illustrate but on a large table I can make an easy screenshot of the result.

I've looked for a solution using something in between likr from stdout to png but I didn't find anything working.

**Comment by jeremycole** [comment]
Howdy lefred!

I added a couple new modes for producing SVG illustrations. Can you try them out? (Most modern browsers can render SVG files!)

**Comment by lefred** [comment]
It works very nice ! And the new parameter to define the width is really what I was missing !

Thank you :D :+1:

**Comment by jeremycole** [comment]
Woot!
