### ISSUE TITLE
unable to run innodb_space 

### ISSUE THREAD

**Issue by shenroong** [jeremycole/innodb_ruby#27]
My system is 14.04 Ubuntu and the newest version of ruby. 

I tried to install inndo_ruby both by sudo gem install innodb_ruby and from repo.
However, when I run innodb_space, it shows 

vagrant@system-lock:/usr/local/mysql/data/test1$ innodb_space 
/usr/local/bin/innodb_space:19:in `load': /var/lib/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:720: syntax error, unexpected ')' (SyntaxError)
/var/lib/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:734: syntax error, unexpected kDO_BLOCK, expecting kEND
  identifiers.sort.each do |identifier, description|
                          ^
/var/lib/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:734: syntax error, unexpected '|', expecting '='
/var/lib/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:758: syntax error, unexpected kEND, expecting $end
	from /usr/local/bin/innodb_space:19

**Comment by keyganker** [comment]
I have the same problem, @jeremycole
