### ISSUE TITLE
Jeremy  here couple of patch if u like to fix a couple of issues

### ISSUE THREAD

**Issue by Tusamarco** [jeremycole/innodb_ruby#33]
Or if u allow me to write in a branch I can push there
# Patch 1

From 067b47daff3934ad7cc96859f4be5ec371882be6 Mon Sep 17 00:00:00 2001
From: Tusamarco tusamarco@gmail.com
Date: Thu, 7 Jan 2016 20:19:39 -0500
Subject: [PATCH] Convert to string given not possible to cast and need to be
 pure String not Array to be accepted by basename

---

 bin/innodb_space | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/bin/innodb_space b/bin/innodb_space
index 1d3df64..b883dfd 100644
--- a/bin/innodb_space
+++ b/bin/innodb_space
@@ -458,6 +458,7 @@ def space_index_pages_free_plot(space, image, start_page)
   end

   image_file = image + "_free.png"
+
   # Aim for one horizontal pixel per extent, but min 1k and max 10k width.
   image_width = [10000, [1000, space.pages / space.pages_per_extent].max].min

@@ -1813,8 +1814,8 @@ when "space-summary"
   space_summary(space, @options.page || 0)
 when "space-index-pages-summary"
   space_index_pages_summary(space, @options.page || 0)
-when "space-index-pages-free-plot"
-  name = File.basename(@options.space_file).sub(".ibd", "")
-  when "space-index-pages-free-plot"
-  name = File.basename(@options.space_file.first.to_s).sub(".ibd", "")
  space_index_pages_free_plot(space, name, @options.page || 0)
  when "space-page-type-regions"
   space_page_type_regions(space, @options.page || 0)
  -- 
  2.6.2
# 
# Patch 2

From 02e037e5808eb3230f1bcfdde821c272d7177b4d Mon Sep 17 00:00:00 2001
From: Tusamarco tusamarco@gmail.com
Date: Thu, 7 Jan 2016 20:22:03 -0500
Subject: [PATCH] Uncomment the data type reference or an NIL issue will be
 generated any time the array value is selected

---

 lib/innodb/data_dictionary.rb | 12 ++++++------
 1 file changed, 6 insertions(+), 6 deletions(-)

diff --git a/lib/innodb/data_dictionary.rb b/lib/innodb/data_dictionary.rb
index e22af06..e7cad98 100644
--- a/lib/innodb/data_dictionary.rb
+++ b/lib/innodb/data_dictionary.rb
@@ -70,17 +70,17 @@ class Innodb::DataDictionary
   # A hash of MySQL's internal type system to the stored
   # values for those types, and the "external" SQL type.
   MYSQL_TYPE = {
-  # :DECIMAL      => { :value => 0,   :type => :DECIMAL     },
-    :DECIMAL      => { :value => 0,   :type => :DECIMAL     },
   :TINY         => { :value => 1,   :type => :TINYINT     },
   :SHORT        => { :value => 2,   :type => :SMALLINT    },
   :LONG         => { :value => 3,   :type => :INT         },
   :FLOAT        => { :value => 4,   :type => :FLOAT       },
   :DOUBLE       => { :value => 5,   :type => :DOUBLE      },
-  # :NULL         => { :value => 6,   :type => nil          },
-    :NULL         => { :value => 6,   :type => nil          },
   :TIMESTAMP    => { :value => 7,   :type => :TIMESTAMP   },
   :LONGLONG     => { :value => 8,   :type => :BIGINT      },
   :INT24        => { :value => 9,   :type => :MEDIUMINT   },
-  # :DATE         => { :value => 10,  :type => :DATE        },
-    :DATE         => { :value => 10,  :type => :DATE        },
   :TIME         => { :value => 11,  :type => :TIME        },
   :DATETIME     => { :value => 12,  :type => :DATETIME    },
   :YEAR         => { :value => 13,  :type => :YEAR        },
  @@ -88,13 +88,13 @@ class Innodb::DataDictionary
   :VARCHAR      => { :value => 15,  :type => :VARCHAR     },
   :BIT          => { :value => 16,  :type => :BIT         },
   :NEWDECIMAL   => { :value => 246, :type => :CHAR        },
-  # :ENUM         => { :value => 247, :type => :ENUM        },
-  # :SET          => { :value => 248, :type => :SET         },
-    :ENUM         => { :value => 247, :type => :ENUM        },
-    :SET          => { :value => 248, :type => :SET         },
   :TINY_BLOB    => { :value => 249, :type => :TINYBLOB    },
   :MEDIUM_BLOB  => { :value => 250, :type => :MEDIUMBLOB  },
   :LONG_BLOB    => { :value => 251, :type => :LONGBLOB    },
   :BLOB         => { :value => 252, :type => :BLOB        },
-  # :VAR_STRING   => { :value => 253, :type => :VARCHAR     },
-    :VAR_STRING   => { :value => 253, :type => :VARCHAR     },
   :STRING       => { :value => 254, :type => :CHAR        },
   :GEOMETRY     => { :value => 255, :type => :GEOMETRY    },
  }
  -- 
  2.6.2

**Comment by jeremycole** [comment]
Howdy Marco. Thanks for using innodb_ruby and contributing to it. :+1:

You can use the "fork" feature on GitHub to fork the repository into your own account, where you can then make commits and propose them for merging via pull requests. It's much better and easier than pasting patches here. :)

I went ahead and fixed the issue you addressed in "Patch 1", but in a slightly different manner in bdc5e38 – please check it out!

As for "Patch 2": could you provide a reproduction case? I don't quite understand what you're trying to do and where/what it's causing a problem with.

**Comment by Tusamarco** [comment]
true to both and I did a fork some time ago but branching would be easier for later merge.
Will post the case about patch 2 soon, but mainly it happens when you dump the set of records.
