### ISSUE TITLE
run problem 

### ISSUE THREAD

**Issue by liuqian1990** [jeremycole/innodb_ruby#37]
innodb_space ...
/usr/bin/innodb_space:19:in `load': /usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:720: syntax error, unexpected ')' (SyntaxError)
/usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:734: syntax error, unexpected kDO_BLOCK, expecting kEND
  identifiers.sort.each do |identifier, description|
                          ^
/usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:734: syntax error, unexpected '|', expecting '='
/usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.13/bin/innodb_space:758: syntax error, unexpected kEND, expecting $end
    from /usr/bin/innodb_space:19

 714   block_x = 0
 715   block_y += 10
 716   puts svg_extent_legend(
 717     graphic_x + block_x,
 718     graphic_y + block_y,
 719     **block_size,** // This line remove the semicolon normally
 720   )

**Comment by jeremycole** [comment]
Support for SVG was removed some time ago.
