### ISSUE TITLE
innodb_space record-dump fails with undefined method error

### ISSUE THREAD

**Issue by midenok** [jeremycole/innodb_ruby#39]
```
innodb_space -s ibdata1 -T test/compact_char -p 1 -R 1 record-dump
Traceback (most recent call last):
        1: from /home/midenok/src/mariadb/innodb_ruby/bin/innodb_space:2083:in `<main>'
/home/midenok/src/mariadb/innodb_ruby/bin/innodb_space:1398:in `record_dump': undefined method `record' for #<Innodb::Page::IbufBitmap:0x0000558ec2218940> (NoMethodError)
```

**Comment by jeremycole** [comment]
Page number 1 is unlikely to be a valid index page so it was likely correctly identified as a `IbufBitmap` for which `record-dump` would be invalid.

**Comment by midenok** [comment]
I don't understand. The error message is illegible, the traceback means that the code does not handle this situation correctly. Please fix this case and print out human-readable error message.
