### ISSUE TITLE
innodb_space run error: BinData requires ruby >= 1.9.3

### ISSUE THREAD

**Issue by feelwing1314** [jeremycole/innodb_ruby#40]
[root@node2 ruby-2.2.10]# innodb_space 
/usr/lib/ruby/gems/1.8/gems/bindata-2.4.3/lib/bindata.rb:5: BinData requires ruby >= 1.9.3. Use BinData version 1.8.x instead (RuntimeError)
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.15/lib/innodb/util/buffer_cursor.rb:3
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.15/lib/innodb.rb:20
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/innodb_ruby-0.9.15/bin/innodb_space:6
	from /usr/bin/innodb_space:19:in `load'
	from /usr/bin/innodb_space:19
[root@node2 ruby-2.2.10]# 

[root@node2 ruby-2.2.10]# ruby -v
**ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux]**
[root@node2 ruby-2.2.10]#

**Comment by jeremycole** [comment]
This is really stale. These days you should be on Ruby 2.6+ at least.
