### ISSUE TITLE
On a clean Ruby 2.7.1p83 install on Windows 10 (64-bit), when I run I get this error:

### ISSUE THREAD

**Issue by clemence97** [jeremycole/innodb_ruby#43]
Traceback (most recent call last):
        1: from bin/innodb_space:1835:in `<main>'
bin/innodb_space:1835:in `trap': unsupported signal `SIGPIPE' (ArgumentError)

**Comment by feihongxiansen** [comment]
> Traceback (most recent call last):
> 1: from bin/innodb_space:1835:in `<main>' bin/innodb_space:1835:in `trap': unsupported signal `SIGPIPE' (ArgumentError)

Because of you System not support command Signal.trap("PIPE") , you can use 'puts Signal.list' look your system support list, my resolve method is edit file 'innodb_space' remove '# Signal.trap("PIPE") { exit }' on 1835 line.
