### ISSUE TITLE
Incorrect path for output file in space-index-pages-free-plot mode

### ISSUE THREAD

**Issue by J-keaper** [jeremycole/innodb_ruby#90]
When I run `innodb_space` in `space-index-pages-free-plot`, I encountered the following error:
```
$ innodb_space -f ./t.ibd space-index-pages-free-plot
Wrote _/t_free.png

gnuplot> set output "_/t_free.png"
                                  ^
         line 0:          cannot open file; output not changed
system error: No such file or directory
```
But when I change the parent directory, and repeat the above command, everything is ok:
```
$ innodb_space -f test/t.ibd space-index-pages-free-plot
Wrote test_t_free.png
```

Then I check the code , I found that it could not get the correct output file name when the file specified by '-f' is in the current directory. 

Is this a bug? or on purpose?

Please check it. Thanks~

**Comment by J-keaper** [comment]
I create a pull request for this issue, it should be useful. #91

**Comment by jeremycole** [comment]
Thanks for the report. The actual "bug" here is that the `sub` on that line should've been a `gsub`, but that results in kind of silly filenames starting with `__` for `./` paths. Fixing in https://github.com/jeremycole/innodb_ruby/pull/92.

**Comment by jeremycole** [comment]
FYI, I release 0.11.0 which includes this and a handful of additional fixes!
